#ifndef CHEATS_H
#define CHEATS_H

#include "plugin.h"

void	All_Status_Max(void);
void	Max_Health(void);
void	Max_Food(void);
void	Max_Water(void);
void	Max_Battery(void);
void	Always_Day_vOne(void);
void	Faster_Load_Times(void);
void	Online_Name__CrackoTwoNineEight(void);
void	Online_Name__Owl__Gbc(void);
void	Online_Name__DarkCrowL(void);
void	Online_Name__Gage_C_NC(void);
void	Online_Name__goldfishRX(void);
void	Online_Name__VIRUS_KOneNG(void);
void	Online_Name__TIME_BOMB_(void);
void	Online_Name__Zamasu_EXE(void);
void	Online_Name__Hunter_CAT(void);
void	Online_Name__GamerX_CAT(void);
void	Online_Name__TumpetTwoZeroOneNine(void);
void	Online_Name__Spring_FiveOneTwo(void);
void	Online_Name__ImNotNoxii(void);
void	Online_Name____Yunix__(void);
void	Online_Name__Ixar(void);
void	Online_Name__Sage(void);
void	Online_Name__Aber(void);
void	Online_Name__BluKrono(void);
void	Online_Name__MarineOne(void);
void	Online_Name__RIZeroT_PGM(void);
void	Online_Name__FCSevenuSeven(void);
void	Online_Name__Nova(void);
void	Offline_ID__DEAD_FACE(void);
void	Offline_ID__DEAD(void);
void	Offline_ID__DECAF_DEAD_FACED(void);
void	Offline_ID__DEAD_FADED_BED(void);
void	Offline_ID__OneTwoThreeFourFiveSixSevenEight(void);
void	Offline_ID__OneOneOneOneOneOneOneOne(void);
void	Offline_ID__TwoTwoTwoTwoTwoTwoTwoTwo(void);
void	Offline_ID__ThreeThreeThreeThreeThreeThreeThreeThree(void);
void	Offline_ID__FourFourFourFourFourFourFourFour(void);
void	Offline_ID__FiveFiveFiveFiveFiveFiveFiveFive(void);
void	Offline_ID__SixSixSixSixSixSixSixSix(void);
void	Offline_ID__SevenSevenSevenSevenSevenSevenSevenSeven(void);
void	Offline_ID__EightEightEightEightEightEightEightEight(void);
void	Offline_ID__NineNineNineNineNineNineNineNine(void);
void	Save_Load_Messages(void);
void	Chat_Spammer(void);
void	Uppercase_Lowercase_Keyboard(void);
void	Special_Symbol_Keyboard(void);
void	Animated_Text_vTwo(void);
void	Messages_App_Custom_Colour(void);
void	People_App_UI_Colours(void);
void	Data_Select_Menu_Custom_Colours(void);
void	Customizable_Quit_Menu(void);
void	Cleaner_Action_UI(void);

#endif
